name: Read JSON from URL

on:
  push:
    branches:
      - main

jobs:
  read-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch JSON
        run: |
          curl -s 'https://backloggd-api.vercel.app/user/laosioor/' -o backloggd.json

      - name: Process JSON with jq
        run: |
          cat backloggd.json | jq '.content.favoriteGames'
